import {test,expect} from '@playwright/test';
test('기록 라벨 개별 설정, 일괄 적용, 복원',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.locator('#map-active-project-badge')).toContainText('기본 프로젝트');
 await page.locator('#geoJsonInput').setInputFiles('tests/fixtures/photo-project.geojson');
 await expect(page.locator('#app-dialog-overlay')).toBeVisible();
 await page.locator('#app-dialog-overlay .primary').click();
 await page.locator('#map-active-project-badge').click();
 await page.locator('#tab-btn-record').click();
 await page.locator('.survey-item .btn-more').first().click();
 await expect(page.locator('#record-menu-label')).toContainText('라벨 표시');
 await expect(page.locator('#record-menu-label line')).toHaveCount(0);
 await page.locator('#record-menu-label').click();
 await expect(page.locator('#record-label-modal')).toBeVisible();
 await expect(page.locator('#record-label-title')).toHaveText('라벨 설정');
 await page.locator('#record-label-modal select[name=mode]').selectOption('text');
 await page.locator('#record-label-modal textarea').fill('현장 라벨');
 await page.locator('#record-label-modal select[name=fontSize]').selectOption('20');
 await page.locator('#record-label-modal input[name=color]').fill('#c026d3');
 await page.locator('#record-label-modal input[name=italic]').check();
 await page.locator('#record-label-modal button[type=submit]').click();
 await expect(page.locator('.record-label-indicator')).toHaveCount(1);
 await expect(page.locator('.record-label-indicator text')).toHaveText('abc');
 await page.locator('.record-label-indicator').click();
 await expect(page.locator('#record-label-title')).toHaveText('라벨 설정');
 await expect(page.locator('#record-label-modal textarea')).toHaveValue('현장 라벨');
 await expect(page.locator('#record-label-modal select[name=fontSize]')).toHaveValue('20');
 await expect(page.locator('#record-label-modal input[name=color]')).toHaveValue('#c026d3');
 await expect(page.locator('#record-label-modal input[name=bold]')).toBeChecked();
 await expect(page.locator('#record-label-modal input[name=italic]')).toBeChecked();
 await page.locator('#record-label-modal .label-default').click();
 await expect(page.locator('#record-label-modal select[name=mode]')).toHaveValue('field');
 await expect(page.locator('#record-label-modal select[name=field]')).toHaveValue('name');
 await expect(page.locator('#record-label-modal select[name=fontSize]')).toHaveValue('13');
 await expect(page.locator('#record-label-modal input[name=color]')).toHaveValue('#111111');
 await expect(page.locator('#record-label-modal input[name=bold]')).toBeChecked();
 await expect(page.locator('#record-label-modal input[name=italic]')).not.toBeChecked();
 await page.locator('#record-label-modal .label-cancel').click();
 await page.locator('.survey-item .btn-more').first().click();
 await expect(page.locator('#record-menu-label')).toContainText('라벨 끄기');
 await expect(page.locator('#record-menu-label line')).toHaveCount(1);
 await page.locator('#record-menu-label').click();
 await expect(page.locator('.record-label-indicator')).toHaveCount(0);
 await page.locator('#record-selection-toggle').click();
 await page.locator('#chk-select-all').check();
 await expect(page.locator('[data-record-bulk-action][onclick*="openRecordLabelSettings"] svg text')).toHaveText('abc');
 await page.evaluate(()=>window.openRecordLabelSettings('selected'));
 await expect(page.locator('.label-count')).toHaveText('3개 기록에 적용');
 await page.locator('#record-label-modal select[name=mode]').selectOption('text');
 await page.locator('#record-label-modal textarea').fill('<b>공통 라벨</b>');
 await page.locator('#record-label-modal button[type=submit]').click();
 await page.locator('#record-selection-toggle').click();
 await page.locator('.survey-info').last().click();
 await page.evaluate(()=>window.closeSidebar());
 await expect(page.locator('.record-map-label').first()).toContainText('<b>공통 라벨</b>');
 const pointLabelGap = await page.evaluate(() => {
  const labels = [...document.querySelectorAll('.record-map-label')].filter(element => element.getClientRects().length).map(element => element.getBoundingClientRect());
  const markers = [...document.querySelectorAll('.leaflet-marker-icon')].filter(element => element.getClientRects().length);
  const pairs = markers.flatMap(marker => {
   const markerRect = marker.getBoundingClientRect();
   return labels.map(labelRect => ({markerRect,labelRect,distance:Math.abs((markerRect.left+markerRect.right-labelRect.left-labelRect.right)/2)+Math.abs(markerRect.top-labelRect.bottom)}));
  }).sort((a,b)=>a.distance-b.distance);
  return pairs[0].markerRect.top-pairs[0].labelRect.bottom;
 });
 expect(pointLabelGap).toBeGreaterThanOrEqual(1);
 expect(pointLabelGap).toBeLessThanOrEqual(3.5);
 const labelCoversPointMarker = await page.evaluate(() => {
  const labels = [...document.querySelectorAll('.record-map-label')].filter(element => element.getClientRects().length).map(element => element.getBoundingClientRect());
  const markers = [...document.querySelectorAll('.leaflet-marker-icon')].filter(element => element.getClientRects().length).map(element => element.getBoundingClientRect());
  return labels.some(label => markers.some(marker => label.left < marker.right && label.right > marker.left && label.top < marker.bottom && label.bottom > marker.top));
 });
 expect(labelCoversPointMarker).toBe(false);
 await page.locator('.record-map-label').first().click();
 await expect(page.locator('#record-label-title')).toHaveText('라벨 설정');
 await expect(page.locator('#record-label-modal textarea')).toHaveValue('<b>공통 라벨</b>');
 await page.locator('#record-label-modal textarea').fill('수정한 라벨');
 await page.locator('#record-label-modal button[type=submit]').click();
 await expect(page.locator('.record-map-label').first()).toContainText('수정한 라벨');
 await page.reload();
 await page.locator('#map-active-project-badge').click();
 await page.locator('#tab-btn-record').click();
 await expect(page.locator('.record-label-indicator')).toHaveCount(3);
 await page.locator('.survey-item .survey-info').first().click();
 await page.locator('#bottom-sheet-more-btn').click();
 await expect(page.locator('#bottom-sheet-label-item')).toContainText('라벨 끄기');
 await expect(page.locator('#bottom-sheet-label-item line')).toHaveCount(1);
 await page.locator('#bottom-sheet-label-item').click();
 await expect(page.locator('.record-label-indicator')).toHaveCount(2);
 await page.evaluate(()=>window.closeBottomSheet());
 await page.locator('#map-active-project-badge').click();
 await page.locator('#tab-btn-record').click();
 await page.locator('.survey-item .btn-more').nth(1).click();
 await expect(page.locator('#record-menu-label')).toContainText('라벨 끄기');
 await page.locator('#record-menu-label').click();
 await expect(page.locator('.record-label-indicator')).toHaveCount(1);
 expect(errors).toEqual([]);
});
